apiVersion: <pipelines_api_version>
kind: Pipeline
metadata:
  name: ${1:app-deploy}
spec:
  resources:
    - name: ${2:pipeline-resource-type}
      type: ${3:pipeline-type}
  tasks:
    - name: ${4:taskName}
      taskRef:
        name: ${5:build-app}
