apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ${1:git-source}
spec:
  type: ${2|git,image,pullRequest,cluster,storage|}
  $LINE_COMMENT params:
    $LINE_COMMENT Check https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pipelineresources for more applicable parameters