apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${1:app-deploy}
spec:
  tasks:
    - name: ${2:taskName}
      taskRef:
        name: ${3:buildah}
    - name: ${4:taskName}
      taskRef:
        name: ${5:maven}
    - name: ${6:taskName}
      taskRef:
        name: ${7:kubectl}
