apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${1:app-deploy}
spec:
  tasks:
    - name: ${2:taskName}
      taskRef:
        name: ${3:taskRefName}
      conditions:
        - conditionRef: ${4:conditionRefName}
