# This is a basic workflow

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up Node
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.11.0

      # Run install dependencies
      - name: Install dependencies
        run: npm i

      # Build extension
      - name: Run prepublish
        run: npm run vscode:prepublish

      # Run tests
      - name: Run Test
        uses: GabrielBB/xvfb-action@fe2609f8182a9ed5aee7d53ff3ed04098a904df2 #v1.0
        with:
          run: npm test --silent

      # Upload coverage to codecov.io
      - name: Codecov
        uses: codecov/codecov-action@07127fde53bc3ccd346d47ab2f14c390161ad108 #v1.0.12
        if: runner.os == 'Linux'
